import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { describe, expect, it } from 'vitest'

const source = readFileSync(
  resolve(process.cwd(), 'src/components/public/PageBlockRenderer.vue'),
  'utf8'
)
const aboutPage = readFileSync(resolve(process.cwd(), 'src/pages/public/AboutPage.vue'), 'utf8')
const researchPage = readFileSync(resolve(process.cwd(), 'src/pages/public/ResearchPage.vue'), 'utf8')
const homePage = readFileSync(resolve(process.cwd(), 'src/pages/public/PublicHomePage.vue'), 'utf8')
const composedPage = readFileSync(resolve(process.cwd(), 'src/pages/public/ComposedPage.vue'), 'utf8')
const composedPageData = readFileSync(resolve(process.cwd(), 'src/composables/useComposedPageData.js'), 'utf8')
const composer = readFileSync(resolve(process.cwd(), 'src/components/admin/AdminPageBlockComposer.vue'), 'utf8')
const publicLayout = readFileSync(resolve(process.cwd(), 'src/layouts/PublicLayout.vue'), 'utf8')
const siteHeader = readFileSync(resolve(process.cwd(), 'src/components/public/SiteHeader.vue'), 'utf8')
const siteFooter = readFileSync(resolve(process.cwd(), 'src/components/public/SiteFooter.vue'), 'utf8')
const navigationPage = readFileSync(resolve(process.cwd(), 'src/pages/admin/AdminNavigationPage.vue'), 'utf8')
const settingsPage = readFileSync(resolve(process.cwd(), 'src/pages/admin/AdminSiteSettingsPage.vue'), 'utf8')
const pagesAdmin = readFileSync(resolve(process.cwd(), 'src/pages/admin/AdminPagesPage.vue'), 'utf8')
const blockController = readFileSync(resolve(process.cwd(), '../backend/src/main/java/ir/tahamohamadi/content/page/api/admin/AdminPageBlockController.java'), 'utf8')

describe('public page block renderer contract', () => {
  it('keeps the composer to an allowlisted set of SSR-safe block types', () => {
    expect(source).toContain("'hero'")
    expect(source).toContain("'rich-text'")
    expect(source).toContain("'call-to-action'")
    expect(source).toContain('supportedBlocks.has(block.type)')
  })

  it('uses the existing safe Markdown boundary and rejects unsafe action paths', () => {
    expect(source).toContain("MarkdownContent from 'src/components/content/MarkdownContent.vue'")
    expect(source).toContain("/^\\/(fa|en)(?:\\/|$)/")
    expect(source).not.toContain('v-html')
  })

  it('allows the CMS response to opt static pages into the block renderer without changing route ownership', () => {
    expect(aboutPage).toContain('PageBlockRenderer')
    expect(researchPage).toContain('PageBlockRenderer')
    expect(aboutPage).toContain('page?.blocks?.length')
    expect(researchPage).toContain('page?.blocks?.length')
    expect(homePage).toContain('homeBlocks')
    expect(homePage).toContain(':hero-heading-level="1"')
    expect(homePage).toContain('hasLegacyManagedContent')
    expect(homePage).toContain('PUBLIC_SITE_IDENTITY_KEY')
    expect(homePage).not.toContain('TAHA MOHAMADI')
    expect(composedPage).toContain('PageBlockRenderer')
    expect(composedPage).toContain('useComposedPageData')
    expect(composedPageData).toContain("currentApi.getPage(locale.value, slug.value)")
  })

  it('keeps one document-level heading for a CMS-composed home and renders its supported typed data', () => {
    expect(source).toContain('primaryHeroAvailable')
    expect(source).toContain("block.headingLevel === 1 ? 'h1' : 'h2'")
    expect(source).toContain("block.type === 'collection'")
    expect(source).toContain('item?.canonicalPath')
    expect(source).toContain('page-block__collection-card')
    expect(source).toContain("block.type === 'skills'")
    expect(source).toContain("block.type === 'social-links'")
    expect(source).toContain('collectionItems[source]')
    expect(composedPageData).toContain('currentApi.listPosts')
    expect(composedPageData).toContain('currentApi.listPortfolio')
    expect(composedPageData).toContain('currentApi.listPublications')
    expect(composedPageData).toContain('currentApi.getSkills')
    expect(composedPageData).toContain('currentApi.getSocialLinks')
  })

  it('keeps the administrative composer typed and selects media from the existing library', () => {
    expect(composer).toContain("'HERO', 'RICH_TEXT', 'MEDIA'")
    expect(composer).toContain('AdminMediaSelector')
    expect(composer).toContain("createUnsavedChangesGuard")
    expect(composer).toContain('onBlockTypeChange')
    expect(composer).toContain('supportsMarkdown')
    expect(composer).toContain('supportsAction')
    expect(composer).toContain("['HERO', 'CALL_TO_ACTION'")
    expect(composer).toContain('supportsAlt')
    expect(composer).toContain('PageBlockRenderer')
    expect(composer).toContain('previewBlocks')
    expect(composer).toContain('previewOpen')
    expect(composer).toContain('collectionOptions')
    expect(composer).toContain('emit-value map-options')
    expect(composer).toContain("t('admin.composer.previewTitle')")
    expect(composer).toContain('validateActionPaths')
    expect(composer).toContain("block.type === 'MEDIA'")
    expect(composer).toContain('Boolean(block.settings?.mediaId && value.alt)')
    expect(composer).toContain('mapValidationErrors')
    expect(composer).toContain('<q-dialog v-model="removalOpen" persistent>')
    expect(composer).toContain("t('admin.composer.remove'")
    expect(composer).toContain('aria-live="polite"')
    expect(composer).toContain('data-composer-block-index')
    expect(composer).toContain('/blocks/composition')
    expect(composer).toContain('/preview-token')
    expect(composer).toContain('/api/v1/preview/pages/')
    expect(composer).toContain('serverPreviewBlocks')
    expect(composer).toContain("t('admin.composer.previewSavedDraft')")
    expect(composer).toContain('autosaveState')
    expect(composer).toContain('setTimeout(() => { void save(true) }, 1500)')
    expect(composer).toContain("props.pageStatus === 'DRAFT'")
    expect(composer).toContain('addSection')
    expect(composer).toContain('moveSection')
    expect(composer).toContain('sectionOptions')
    expect(composer).toContain('tabindex="-1"')
    expect(composer).toContain("t('admin.composer.removeTitle')")
    expect(composer).toContain("t('admin.composer.moved'")
    expect(composer).not.toContain('v-html')
  })

  it('fails closed for meaningful media without localized alt and makes decorative media explicit', () => {
    expect(composer).toContain('decorative')
    expect(source).toContain('isDecorativeMedia')
    expect(source).toContain('mediaRenderable')
    expect(blockController).toContain('validateMediaAccessibility')
    expect(blockController).toContain('Decorative media must not have alt text')
    expect(blockController).toContain('Meaningful media requires localized alt text')
  })

  it('loads CMS-backed shell data through the SSR snapshot boundary', () => {
    expect(publicLayout).toContain('currentApi.getSiteChrome(language.value)')
    expect(publicLayout).toContain('PUBLIC_SITE_IDENTITY_KEY')
    expect(publicLayout).toContain('siteChrome.identity || siteChrome.navigation?.length')
    expect(publicLayout).toContain("property: 'og:image'")
    expect(publicLayout).toContain("public-shell--standard-density")
    expect(publicLayout).toContain('data-theme-preset')
    expect(siteHeader).toContain('rel="noopener noreferrer"')
    expect(siteHeader).toContain('var(--tm-radius-control)')
    expect(siteHeader).toContain('Array.isArray(props.navigation)')
    expect(siteHeader).not.toContain('props.navigation.length')
    expect(publicLayout).toContain('siteChrome.identity || siteChrome.navigation?.length')
    expect(siteHeader).toContain("item.targetPath.replace('{lang}', props.locale)")
    expect(siteFooter).toContain('footerStatement')
    expect(siteFooter).toContain('footerAvailability')
    expect(siteFooter).toContain('footerRights')
    expect(navigationPage).toContain("t('admin.navigation.moveUp'")
    expect(navigationPage).toContain('validateTargets')
    expect(navigationPage).toContain('<q-dialog v-model="removalOpen" persistent>')
    expect(settingsPage).toContain('AdminLocaleTabs')
    expect(settingsPage).toContain('themeOptions')
    expect(settingsPage).toContain('densityOptions')
    expect(settingsPage).toContain('emit-value map-options')
    expect(settingsPage).toContain('form.value?.translations?.[selectedLocale.value]')
    expect(settingsPage).toContain("target=\"_blank\"")
    expect(settingsPage).toContain('footerStatement')
    expect(settingsPage).toContain('footerAvailability')
    expect(settingsPage).toContain('footerRights')
    expect(pagesAdmin).toContain('mapValidationErrors')
    expect(pagesAdmin).toContain('createUnsavedChangesGuard')
    expect(pagesAdmin).toContain('admin-pages__translation-summary')
    expect(pagesAdmin).not.toContain('·')
    expect(pagesAdmin).toContain("/${locale}/pages/${slug}")
  })
})
