package ir.tahamohamadi.publicsite.api;

import ir.tahamohamadi.common.domain.LanguageCode;
import ir.tahamohamadi.content.featured.api.publicsite.PublicFeaturedResponse;
import ir.tahamohamadi.content.featured.api.publicsite.PublicFeaturedService;
import ir.tahamohamadi.content.social.api.publicsite.PublicSocialLinkService;
import ir.tahamohamadi.content.social.api.publicsite.PublicSocialLinksResponse;
import ir.tahamohamadi.seo.SeoMetadataResponse;
import ir.tahamohamadi.seo.OpenGraphMediaResponse;
import ir.tahamohamadi.seo.HreflangResponse;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.NoSuchElementException;

@Service @Transactional(readOnly = true)
public class PublicContentService {
    private final JdbcTemplate jdbc;
    private final PublicFeaturedService featured;
    private final PublicSocialLinkService socialLinks;
    public PublicContentService(JdbcTemplate jdbc,PublicFeaturedService featured,PublicSocialLinkService socialLinks) { this.jdbc = jdbc; this.featured=featured; this.socialLinks=socialLinks; }

    public PageDetail page(LanguageCode lang,String slug) { List<PageDetail> rows=jdbc.query("select p.id page_id,p.page_key,t.slug,t.title,t.summary,t.body_markdown,t.seo_title,t.seo_description,t.canonical_path,t.og_media_id,t.updated_at from content_page_translation t join content_page p on p.id=t.content_page_id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->page(rs,lang),lang.name(),slug); if(rows.isEmpty())throw missingPage(slug); PageDetail current=rows.getFirst(); UUID pageId=jdbc.queryForObject("select p.id from content_page p join content_page_translation t on t.content_page_id=p.id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",UUID.class,lang.name(),slug); List<Link> actual=pageLinks(pageId); return new PageDetail(current.locale(),actual.stream().map(Link::locale).toList(),current.canonicalPath(),actual,current.seo(),current.ogMedia(),current.lastModified(),current.slug(),current.title(),current.summary(),current.bodyMarkdown()); }
    public Listing<PostItem> posts(LanguageCode lang,String q,String category,String tag,int page,int size) { String sql="select t.slug,t.title,t.excerpt,p.published_at,t.seo_title,t.seo_description,t.updated_at from blog_post_translation t join blog_post p on p.id=t.blog_post_id join blog_category c on c.id=p.category_id where t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp and c.deleted_at is null and c.is_active"+(category==null?"":" and exists(select 1 from blog_category_translation x where x.blog_category_id=c.id and x.language_code=? and lower(x.slug)=lower(?) and x.deleted_at is null)")+(tag==null?"":" and exists(select 1 from blog_post_tag b join tag g on g.id=b.tag_id join tag_translation x on x.tag_id=g.id where b.blog_post_id=p.id and g.is_active and g.deleted_at is null and x.language_code=? and lower(x.slug)=lower(?) and x.deleted_at is null)")+(q==null?"":" and t.search_vector @@ plainto_tsquery(case when ?='en' then 'english'::regconfig else 'simple'::regconfig end,?)"); java.util.ArrayList<Object> args=new java.util.ArrayList<>(List.of(lang.name())); if(category!=null){args.add(lang.name());args.add(category);} if(tag!=null){args.add(lang.name());args.add(tag);} if(q!=null){args.add(lang.name());args.add(q);} long total=jdbc.queryForObject("select count(*) from ("+sql+") filtered",Long.class,args.toArray()); args.add(size);args.add(page*size); return listing(lang,jdbc.query(sql+" order by p.published_at desc,p.id desc limit ? offset ?",(rs,n)->post(rs,lang),args.toArray()),page,size,"/blog",total); }
    public PostDetail post(LanguageCode lang,String slug){List<PostDetail> rows=jdbc.query("select t.slug,t.title,t.excerpt,t.body_markdown,p.published_at,t.seo_title,t.seo_description,t.updated_at from blog_post_translation t join blog_post p on p.id=t.blog_post_id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->postDetail(rs,lang),lang.name(),slug);if(rows.isEmpty())throw missing("blog_post_translation","blog_post_id","blog_post",slug,"/blog/"); PostDetail current=rows.getFirst(); UUID id=jdbc.queryForObject("select p.id from blog_post p join blog_post_translation t on t.blog_post_id=p.id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",UUID.class,lang.name(),slug); List<Link> links=translationLinks("blog_post_translation","blog_post_id",id,"/blog/"); return new PostDetail(current.locale(),links.stream().map(Link::locale).toList(),current.canonicalPath(),links,current.seo(),current.ogMedia(),current.lastModified(),current.slug(),current.title(),current.excerpt(),current.bodyMarkdown(),current.publishedAt());}
    public Listing<Item> categories(LanguageCode lang) { return listing(lang,jdbc.query("select t.slug,t.name,t.seo_title,t.seo_description,count(pt.blog_post_id) post_count from blog_category_translation t join blog_category c on c.id=t.blog_category_id left join blog_post p on p.category_id=c.id and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp left join blog_post_translation pt on pt.blog_post_id=p.id and pt.language_code=? and pt.deleted_at is null where t.language_code=? and t.deleted_at is null and c.deleted_at is null and c.is_active group by t.id,c.id order by c.sort_order,c.id limit 50",(rs,n)->item(rs,lang,"/categories/"),lang.name(),lang.name()),0,50,"/categories"); }
    public Listing<Item> tags(LanguageCode lang) { return listing(lang,jdbc.query("select t.slug,t.name,t.seo_title,t.seo_description,count(pt.blog_post_id) post_count from tag_translation t join tag g on g.id=t.tag_id left join blog_post_tag b on b.tag_id=g.id left join blog_post p on p.id=b.blog_post_id and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp left join blog_post_translation pt on pt.blog_post_id=p.id and pt.language_code=? and pt.deleted_at is null where t.language_code=? and t.deleted_at is null and g.deleted_at is null and g.is_active group by t.id,g.id order by t.slug,g.id limit 50",(rs,n)->item(rs,lang,"/tags/"),lang.name(),lang.name()),0,50,"/tags"); }
    public Listing<SkillItem> skills(LanguageCode lang) { return skills(lang,50); }
    public Listing<PortfolioItem> projects(LanguageCode lang,String skill,int page,int size) { String sql="select t.slug,t.title,t.summary,t.seo_title,t.seo_description,t.updated_at from portfolio_project_translation t join portfolio_project p on p.id=t.portfolio_project_id where t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED'"+(skill==null?"":" and exists(select 1 from portfolio_project_skill ps join skill s on s.id=ps.skill_id where ps.portfolio_project_id=p.id and s.is_active and s.deleted_at is null and s.skill_key=?)"); Object[] filterArgs=skill==null?new Object[]{lang.name()}:new Object[]{lang.name(),skill}; long total=jdbc.queryForObject("select count(*) from ("+sql+") filtered",Long.class,filterArgs); Object[] args=skill==null?new Object[]{lang.name(),size,page*size}:new Object[]{lang.name(),skill,size,page*size}; return listing(lang,jdbc.query(sql+" order by p.sort_order,p.id limit ? offset ?",(rs,n)->portfolio(rs,lang),args),page,size,"/portfolio",total); }
    public PortfolioDetail project(LanguageCode lang,String slug){List<PortfolioDetail> rows=jdbc.query("select t.slug,t.title,t.summary,t.body_markdown,t.seo_title,t.seo_description,t.updated_at from portfolio_project_translation t join portfolio_project p on p.id=t.portfolio_project_id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED'",(rs,n)->portfolioDetail(rs,lang),lang.name(),slug);if(rows.isEmpty())throw missing("portfolio_project_translation","portfolio_project_id","portfolio_project",slug,"/portfolio/"); PortfolioDetail current=rows.getFirst(); UUID id=jdbc.queryForObject("select p.id from portfolio_project p join portfolio_project_translation t on t.portfolio_project_id=p.id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED'",UUID.class,lang.name(),slug); List<Link> links=translationLinks("portfolio_project_translation","portfolio_project_id",id,"/portfolio/"); return new PortfolioDetail(current.locale(),links.stream().map(Link::locale).toList(),current.canonicalPath(),links,current.seo(),current.ogMedia(),current.lastModified(),current.slug(),current.title(),current.summary(),current.bodyMarkdown());}
    public Home home(LanguageCode lang){ PageDetail page=homePage(lang); PublicFeaturedResponse featuredItems=featured.list(lang,"home",6); PublicSocialLinksResponse socials=socialLinks.list(); List<PostItem> latest=posts(lang,null,null,null,0,6).items(); List<PortfolioItem> projects=projects(lang,null,0,6).items(); List<PublicationItem> publications=jdbc.query("select t.slug,t.title,t.abstract_text,p.year,p.publication_stage from publication_translation t join publication p on p.id=t.publication_id where t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.content_status='PUBLISHED' order by p.year desc,p.sort_order,p.id limit 6",(rs,n)->new PublicationItem(rs.getString(1),rs.getString(2),empty(rs.getString(3)),rs.getInt(4),rs.getString(5)),lang.name()); return new Home(page.locale(),page.availableLocales(),page.canonicalPath(),page.hreflang(),page.seo(),page.ogMedia(),page.lastModified(),new HomePage(page.title(),page.summary(),page.bodyMarkdown()),featuredItems,latest,projects,publications,skills(lang,6),socials); }
    private PageDetail homePage(LanguageCode lang) { List<PageDetail> rows=jdbc.query("select p.page_key,t.slug,t.title,t.summary,t.body_markdown,t.seo_title,t.seo_description,t.canonical_path,t.og_media_id,t.updated_at from content_page_translation t join content_page p on p.id=t.content_page_id where p.page_key='home' and t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->page(rs,lang),lang.name()); if(rows.isEmpty())throw missingHome(); UUID pageId=jdbc.queryForObject("select p.id from content_page p join content_page_translation t on t.content_page_id=p.id where p.page_key='home' and t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",UUID.class,lang.name()); PageDetail current=rows.getFirst(); List<Link> actual=pageLinks(pageId); return new PageDetail(current.locale(),actual.stream().map(Link::locale).toList(),current.canonicalPath(),actual,current.seo(),current.ogMedia(),current.lastModified(),current.slug(),current.title(),current.summary(),current.bodyMarkdown()); }
    private Listing<SkillItem> skills(LanguageCode lang,int size) { return listing(lang,jdbc.query("select s.skill_key,t.name,t.description from skill s join skill_translation t on t.skill_id=s.id join skill_category c on c.id=s.skill_category_id where t.language_code=? and t.deleted_at is null and s.deleted_at is null and s.is_active and c.deleted_at is null and c.is_active order by c.sort_order,s.sort_order,s.id limit ?",(rs,n)->new SkillItem(rs.getString(1),rs.getString(2),empty(rs.getString(3))),lang.name(),size),0,size,"/skills"); }
    private TranslationUnavailableException missingPage(String slug) { List<UUID> pages=jdbc.query("select p.id from content_page p join content_page_translation t on t.content_page_id=p.id where lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->rs.getObject(1,UUID.class),slug); if(pages.isEmpty())throw new NoSuchElementException("Public resource not found"); List<Link> links=pageLinks(pages.getFirst()); return new TranslationUnavailableException(links.stream().map(Link::locale).toList(),links.stream().map(Link::path).toList()); }
    private TranslationUnavailableException missingHome() { List<UUID> pages=jdbc.query("select p.id from content_page p where p.page_key='home' and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->rs.getObject(1,UUID.class)); if(pages.isEmpty())throw new NoSuchElementException("Public resource not found"); List<Link> links=pageLinks(pages.getFirst()); return new TranslationUnavailableException(links.stream().map(Link::locale).toList(),links.stream().map(Link::path).toList()); }
    private TranslationUnavailableException missing(String translationTable,String foreignKey,String resourceTable,String slug,String path) { List<UUID> ids=jdbc.query("select r.id from "+resourceTable+" r join "+translationTable+" t on t."+foreignKey+"=r.id where lower(t.slug)=lower(?) and t.deleted_at is null and r.deleted_at is null and r.status='PUBLISHED'"+(resourceTable.equals("blog_post")?" and r.published_at<=current_timestamp":""),(rs,n)->rs.getObject(1,UUID.class),slug); if(ids.isEmpty())throw new NoSuchElementException("Public resource not found"); List<Link> links=translationLinks(translationTable,foreignKey,ids.getFirst(),path); return new TranslationUnavailableException(links.stream().map(Link::locale).toList(),links.stream().map(Link::path).toList()); }
    private List<Link> translationLinks(String translationTable,String foreignKey,UUID id,String path) { return jdbc.query("select language_code,slug from "+translationTable+" where "+foreignKey+"=? and deleted_at is null order by language_code",(rs,n)->new Link(rs.getString(1),"/"+rs.getString(1)+path+rs.getString(2)),id); }
    private List<Link> pageLinks(UUID pageId) { return jdbc.query("select t.language_code,t.slug,t.canonical_path,p.page_key from content_page_translation t join content_page p on p.id=t.content_page_id where t.content_page_id=? and t.deleted_at is null order by t.language_code",(rs,n)->new Link(rs.getString(1),canonicalPagePath(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4))),pageId); }
    private PageDetail page(ResultSet rs,LanguageCode l)throws SQLException{String s=rs.getString("slug"),canonical=rs.getString("canonical_path"),pageKey=rs.getString("page_key");OpenGraphMediaResponse media=ogMedia(rs,l);return new PageDetail(l.name(),List.of(l.name()),canonicalPagePath(l.name(),s,canonical,pageKey),List.of(),seo(rs,media),media,time(rs,"updated_at"),s,rs.getString("title"),empty(rs.getString("summary")),empty(rs.getString("body_markdown")));}
    private PostItem post(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PostItem(l.name(),List.of(l.name()),"/"+l+"/blog/"+s,List.of(new Link(l.name(),"/"+l+"/blog/"+s)),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("excerpt")),time(r,"published_at"));}
    private PostDetail postDetail(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PostDetail(l.name(),List.of(l.name()),"/"+l+"/blog/"+s,List.of(new Link(l.name(),"/"+l+"/blog/"+s)),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("excerpt")),empty(r.getString("body_markdown")),time(r,"published_at"));}
    private PortfolioItem portfolio(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PortfolioItem(l.name(),List.of(l.name()),"/"+l+"/portfolio/"+s,List.of(new Link(l.name(),"/"+l+"/portfolio/"+s)),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("summary")));}
    private PortfolioDetail portfolioDetail(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PortfolioDetail(l.name(),List.of(l.name()),"/"+l+"/portfolio/"+s,List.of(new Link(l.name(),"/"+l+"/portfolio/"+s)),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("summary")),empty(r.getString("body_markdown")));}
    private Item item(ResultSet r,LanguageCode l,String base)throws SQLException{String s=r.getString("slug");return new Item(l.name(),List.of(l.name()),"/"+l+base+s,List.of(new Link(l.name(),"/"+l+base+s)),seo(r),s,r.getString("name"),r.getLong("post_count"));}
    private static <T> Listing<T> listing(LanguageCode l,List<T> items,int p,int s,String route){return new Listing<>(l.name(),List.of(l.name()),"/"+l+route,List.of(new Link(l.name(),"/"+l+route)),new SeoMetadataResponse(null,null),null,null,items,p,s,items.size(),items.isEmpty()?0:Math.max(1,(int)Math.ceil((double)items.size()/s)));}
    @SuppressWarnings("unchecked")
    private <T> Listing<T> listing(LanguageCode l,List<T> items,int p,int s,String route,long total){List<T> resolved=items;if(!items.isEmpty()&&items.getFirst() instanceof PostItem){resolved=(List<T>)enrichPostAlternates((List<PostItem>)(List<?>)items);}return new Listing<>(l.name(),List.of(l.name()),"/"+l+route,List.of(new Link(l.name(),"/"+l+route)),new SeoMetadataResponse(null,null),null,null,resolved,p,s,total,total==0?0:(int)Math.ceil((double)total/s));}
    private List<PostItem> enrichPostAlternates(List<PostItem> items){String placeholders=String.join(",",java.util.Collections.nCopies(items.size(),"?"));List<Object> args=new java.util.ArrayList<>();args.add(items.getFirst().locale());args.addAll(items.stream().map(PostItem::slug).toList());java.util.Map<String,List<Link>> linksBySlug=new java.util.HashMap<>();jdbc.query("select current.slug current_slug,alternate.language_code,alternate.slug from blog_post_translation current join blog_post p on p.id=current.blog_post_id join blog_post_translation alternate on alternate.blog_post_id=p.id where current.language_code=? and current.slug in ("+placeholders+") and current.deleted_at is null and alternate.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp order by current.slug,alternate.language_code",rs->{linksBySlug.computeIfAbsent(rs.getString("current_slug"),ignored->new java.util.ArrayList<>()).add(new Link(rs.getString("language_code"),"/"+rs.getString("language_code")+"/blog/"+rs.getString("slug")));},args.toArray());return items.stream().map(item->{List<Link> links=linksBySlug.getOrDefault(item.slug(),List.of(new Link(item.locale(),item.canonicalPath())));return new PostItem(item.locale(),links.stream().map(Link::locale).toList(),item.canonicalPath(),links,item.seo(),item.ogMedia(),item.lastModified(),item.slug(),item.title(),item.excerpt(),item.publishedAt());}).toList();}
    private OpenGraphMediaResponse ogMedia(ResultSet r,LanguageCode locale)throws SQLException{UUID id=r.getObject("og_media_id",UUID.class);if(id==null)return null;List<OpenGraphMediaResponse> media=jdbc.query("select mt.alt_text from media_asset m join media_asset_translation mt on mt.media_asset_id=m.id and mt.language_code=? and mt.deleted_at is null where m.id=? and m.status='ACTIVE' and m.deleted_at is null",(rs,n)->new OpenGraphMediaResponse("/api/v1/public/media/"+id,rs.getString("alt_text")),locale.name(),id);return media.isEmpty()?null:media.getFirst();} private static SeoMetadataResponse seo(ResultSet r)throws SQLException{return new SeoMetadataResponse(r.getString("seo_title"),r.getString("seo_description"));} private static SeoMetadataResponse seo(ResultSet r,OpenGraphMediaResponse media)throws SQLException{return new SeoMetadataResponse(r.getString("seo_title"),r.getString("seo_description"),new SeoMetadataResponse.OpenGraphResponse(r.getString("seo_title"),r.getString("seo_description"),media==null?null:media.url()));} private static Instant time(ResultSet r,String c)throws SQLException{var t=r.getTimestamp(c);return t==null?null:t.toInstant();} private static String empty(String v){return v==null?"":v;} private static String canonicalPagePath(String locale,String slug,String canonicalPath,String pageKey){if(canonicalPath!=null&&!canonicalPath.isBlank())return canonicalPath.trim();return "home".equals(pageKey)?"/"+locale:"/"+locale+"/pages/"+slug;}
    public record Link(String locale,String path) implements HreflangResponse {}
    public record Listing<T>(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,List<T> items,int page,int size,long totalElements,int totalPages){}
    public record PageDetail(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,String slug,String title,String summary,String bodyMarkdown){}
    public record PostItem(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,String slug,String title,String excerpt,Instant publishedAt){}
    public record PostDetail(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,String slug,String title,String excerpt,String bodyMarkdown,Instant publishedAt){}
    public record PortfolioItem(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,String slug,String title,String summary){}
    public record PortfolioDetail(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,String slug,String title,String summary,String bodyMarkdown){}
    public record Item(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,String slug,String name,long postCount){}
    public record SkillItem(String key,String name,String description){}
    public record HomePage(String title,String summary,String bodyMarkdown){}
    public record PublicationItem(String slug,String title,String abstractText,int year,String stage){}
    public record Home(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,SeoMetadataResponse seo,OpenGraphMediaResponse ogMedia,Instant lastModified,HomePage page,PublicFeaturedResponse featured,List<PostItem> latestPosts,List<PortfolioItem> selectedProjects,List<PublicationItem> selectedPublications,Listing<SkillItem> skills,PublicSocialLinksResponse socialLinks){}
}
