package ir.tahamohamadi.publicsite.api;

import ir.tahamohamadi.common.domain.LanguageCode;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Instant;
import java.util.List;

@Service @Transactional(readOnly = true)
public class PublicContentService {
    private final JdbcTemplate jdbc;
    public PublicContentService(JdbcTemplate jdbc) { this.jdbc = jdbc; }

    public PageDetail page(LanguageCode lang,String slug) { List<PageDetail> rows=jdbc.query("select t.slug,t.title,t.summary,t.body_markdown,t.seo_title,t.seo_description,t.canonical_path,t.updated_at from content_page_translation t join content_page p on p.id=t.content_page_id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->page(rs,lang),lang.name(),slug); if(rows.isEmpty())throw new TranslationUnavailableException(List.of("en"),List.of("/en/pages/"+slug)); return rows.getFirst(); }
    public Listing<PostItem> posts(LanguageCode lang,String q,String category,String tag,int page,int size) { String sql="select t.slug,t.title,t.excerpt,p.published_at,t.seo_title,t.seo_description,t.updated_at from blog_post_translation t join blog_post p on p.id=t.blog_post_id join blog_category c on c.id=p.category_id where t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp and c.deleted_at is null and c.is_active"+(category==null?"":" and exists(select 1 from blog_category_translation x where x.blog_category_id=c.id and x.language_code=? and lower(x.slug)=lower(?) and x.deleted_at is null)")+(tag==null?"":" and exists(select 1 from blog_post_tag b join tag g on g.id=b.tag_id join tag_translation x on x.tag_id=g.id where b.blog_post_id=p.id and g.is_active and g.deleted_at is null and x.language_code=? and lower(x.slug)=lower(?) and x.deleted_at is null)")+(q==null?"":" and t.search_vector @@ plainto_tsquery(case when ?='en' then 'english'::regconfig else 'simple'::regconfig end,?)")+" order by p.published_at desc,p.id desc limit ? offset ?"; java.util.ArrayList<Object> args=new java.util.ArrayList<>(List.of(lang.name())); if(category!=null){args.add(lang.name());args.add(category);} if(tag!=null){args.add(lang.name());args.add(tag);} if(q!=null){args.add(lang.name());args.add(q);} args.add(size);args.add(page*size); return listing(lang,jdbc.query(sql,(rs,n)->post(rs,lang),args.toArray()),page,size,"/posts"); }
    public PostDetail post(LanguageCode lang,String slug){List<PostDetail> rows=jdbc.query("select t.slug,t.title,t.excerpt,t.body_markdown,p.published_at,t.seo_title,t.seo_description,t.updated_at from blog_post_translation t join blog_post p on p.id=t.blog_post_id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED' and p.published_at<=current_timestamp",(rs,n)->postDetail(rs,lang),lang.name(),slug);if(rows.isEmpty())throw new TranslationUnavailableException(List.of(),List.of());return rows.getFirst();}
    public Listing<Item> categories(LanguageCode lang) { return listing(lang,jdbc.query("select t.slug,t.name,t.seo_title,t.seo_description from blog_category_translation t join blog_category c on c.id=t.blog_category_id where t.language_code=? and t.deleted_at is null and c.deleted_at is null and c.is_active order by c.sort_order,c.id",(rs,n)->item(rs,lang,"/categories/"),lang.name()),0,50,"/categories"); }
    public Listing<Item> tags(LanguageCode lang) { return listing(lang,jdbc.query("select t.slug,t.name,t.seo_title,t.seo_description from tag_translation t join tag g on g.id=t.tag_id where t.language_code=? and t.deleted_at is null and g.deleted_at is null and g.is_active order by t.slug,g.id",(rs,n)->item(rs,lang,"/tags/"),lang.name()),0,50,"/tags"); }
    public Listing<SkillItem> skills(LanguageCode lang) { return listing(lang,jdbc.query("select s.skill_key,t.name,t.description from skill s join skill_translation t on t.skill_id=s.id join skill_category c on c.id=s.skill_category_id where t.language_code=? and t.deleted_at is null and s.deleted_at is null and s.is_active and c.deleted_at is null and c.is_active order by c.sort_order,s.sort_order,s.id",(rs,n)->new SkillItem(rs.getString(1),rs.getString(2),empty(rs.getString(3))),lang.name()),0,50,"/skills"); }
    public Listing<PortfolioItem> projects(LanguageCode lang,String skill,int page,int size) { String sql="select t.slug,t.title,t.summary,t.seo_title,t.seo_description,t.updated_at from portfolio_project_translation t join portfolio_project p on p.id=t.portfolio_project_id where t.language_code=? and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED'"+(skill==null?"":" and exists(select 1 from portfolio_project_skill ps join skill s on s.id=ps.skill_id where ps.portfolio_project_id=p.id and s.is_active and s.deleted_at is null and s.skill_key=?)")+" order by p.sort_order,p.id limit ? offset ?"; Object[] args=skill==null?new Object[]{lang.name(),size,page*size}:new Object[]{lang.name(),skill,size,page*size}; return listing(lang,jdbc.query(sql,(rs,n)->portfolio(rs,lang),args),page,size,"/portfolio"); }
    public PortfolioDetail project(LanguageCode lang,String slug){List<PortfolioDetail> rows=jdbc.query("select t.slug,t.title,t.summary,t.body_markdown,t.seo_title,t.seo_description,t.updated_at from portfolio_project_translation t join portfolio_project p on p.id=t.portfolio_project_id where t.language_code=? and lower(t.slug)=lower(?) and t.deleted_at is null and p.deleted_at is null and p.status='PUBLISHED'",(rs,n)->portfolioDetail(rs,lang),lang.name(),slug);if(rows.isEmpty())throw new TranslationUnavailableException(List.of(),List.of());return rows.getFirst();}
    public Home home(LanguageCode lang){return new Home(lang.name(),List.of(lang.name()),"/"+lang,links(""),new Seo(null,null),null,null,List.of());}
    private PageDetail page(ResultSet rs,LanguageCode l)throws SQLException{String s=rs.getString("slug");return new PageDetail(l.name(),List.of(l.name()),rs.getString("canonical_path")==null?"/"+l+"/pages/"+s:rs.getString("canonical_path"),links("/pages/"+s),seo(rs),null,time(rs,"updated_at"),s,rs.getString("title"),empty(rs.getString("summary")),empty(rs.getString("body_markdown")));}
    private PostItem post(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PostItem(l.name(),List.of(l.name()),"/"+l+"/posts/"+s,links("/posts/"+s),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("excerpt")),time(r,"published_at"));}
    private PostDetail postDetail(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PostDetail(l.name(),List.of(l.name()),"/"+l+"/posts/"+s,links("/posts/"+s),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("excerpt")),empty(r.getString("body_markdown")),time(r,"published_at"));}
    private PortfolioItem portfolio(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PortfolioItem(l.name(),List.of(l.name()),"/"+l+"/portfolio/"+s,links("/portfolio/"+s),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("summary")));}
    private PortfolioDetail portfolioDetail(ResultSet r,LanguageCode l)throws SQLException{String s=r.getString("slug");return new PortfolioDetail(l.name(),List.of(l.name()),"/"+l+"/portfolio/"+s,links("/portfolio/"+s),seo(r),null,time(r,"updated_at"),s,r.getString("title"),empty(r.getString("summary")),empty(r.getString("body_markdown")));}
    private Item item(ResultSet r,LanguageCode l,String base)throws SQLException{String s=r.getString("slug");return new Item(l.name(),List.of(l.name()),"/"+l+base+s,links(base+s),seo(r),s,r.getString("name"));}
    private static <T> Listing<T> listing(LanguageCode l,List<T> items,int p,int s,String route){return new Listing<>(l.name(),List.of(l.name()),"/"+l+route,links(route),new Seo(null,null),null,null,items,p,s);}
    private static Seo seo(ResultSet r)throws SQLException{return new Seo(r.getString("seo_title"),r.getString("seo_description"));} private static Instant time(ResultSet r,String c)throws SQLException{var t=r.getTimestamp(c);return t==null?null:t.toInstant();} private static String empty(String v){return v==null?"":v;} private static List<Link> links(String route){return List.of(new Link("fa","/fa"+route),new Link("en","/en"+route));}
    public record Seo(String title,String description){} public record Link(String locale,String path){} public record Listing<T>(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,List<T> items,int page,int size){} public record PageDetail(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,String slug,String title,String summary,String bodyMarkdown){} public record PostItem(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,String slug,String title,String excerpt,Instant publishedAt){} public record PostDetail(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,String slug,String title,String excerpt,String bodyMarkdown,Instant publishedAt){} public record PortfolioItem(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,String slug,String title,String summary){} public record PortfolioDetail(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,String slug,String title,String summary,String bodyMarkdown){} public record Item(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,String slug,String name){} public record SkillItem(String key,String name,String description){} public record Home(String locale,List<String> availableLocales,String canonicalPath,List<Link> hreflang,Seo seo,Object ogMedia,Instant lastModified,List<Object> items){}
}
