CREATE TABLE site_setting (
    id uuid NOT NULL,
    brand_name varchar(255) NOT NULL,
    brand_tagline varchar(500) NULL,
    logo_media_id uuid NULL,
    og_media_id uuid NULL,
    theme_preset varchar(32) NOT NULL,
    layout_density varchar(32) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid NULL,
    updated_by uuid NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_site_setting PRIMARY KEY (id),
    CONSTRAINT ck_site_setting_brand_name CHECK (btrim(brand_name) <> ''),
    CONSTRAINT ck_site_setting_theme_preset CHECK (theme_preset IN ('EDITORIAL_NAVY')),
    CONSTRAINT ck_site_setting_layout_density CHECK (layout_density IN ('COMFORTABLE', 'STANDARD')),
    CONSTRAINT fk_site_setting_logo_media FOREIGN KEY (logo_media_id) REFERENCES media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_setting_og_media FOREIGN KEY (og_media_id) REFERENCES media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_setting_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_setting_updated_by FOREIGN KEY (updated_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_setting_deleted_by FOREIGN KEY (deleted_by) REFERENCES app_user (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX ux_site_setting_singleton ON site_setting ((1)) WHERE deleted_at IS NULL;

CREATE TABLE site_setting_translation (
    id uuid NOT NULL,
    site_setting_id uuid NOT NULL,
    language_code varchar(2) NOT NULL,
    brand_name varchar(255) NOT NULL,
    brand_tagline varchar(500) NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid NULL,
    updated_by uuid NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_site_setting_translation PRIMARY KEY (id),
    CONSTRAINT uq_site_setting_translation_locale UNIQUE (site_setting_id, language_code),
    CONSTRAINT ck_site_setting_translation_locale CHECK (language_code IN ('fa', 'en')),
    CONSTRAINT ck_site_setting_translation_brand_name CHECK (btrim(brand_name) <> ''),
    CONSTRAINT fk_site_setting_translation_parent FOREIGN KEY (site_setting_id) REFERENCES site_setting (id) ON DELETE CASCADE,
    CONSTRAINT fk_site_setting_translation_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_setting_translation_updated_by FOREIGN KEY (updated_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_setting_translation_deleted_by FOREIGN KEY (deleted_by) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE TABLE site_navigation_item (
    id uuid NOT NULL,
    navigation_key varchar(100) NOT NULL,
    target_path varchar(2048) NOT NULL,
    external_target boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid NULL,
    updated_by uuid NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_site_navigation_item PRIMARY KEY (id),
    CONSTRAINT ck_site_navigation_item_key CHECK (btrim(navigation_key) <> ''),
    CONSTRAINT ck_site_navigation_item_order CHECK (sort_order >= 0),
    CONSTRAINT fk_site_navigation_item_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_navigation_item_updated_by FOREIGN KEY (updated_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_navigation_item_deleted_by FOREIGN KEY (deleted_by) REFERENCES app_user (id) ON DELETE SET NULL
);
CREATE INDEX ix_site_navigation_item_active_order ON site_navigation_item (is_active, sort_order, id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ux_site_navigation_item_key_active ON site_navigation_item (navigation_key) WHERE deleted_at IS NULL;

CREATE TABLE site_navigation_item_translation (
    id uuid NOT NULL,
    site_navigation_item_id uuid NOT NULL,
    language_code varchar(2) NOT NULL,
    label varchar(255) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid NULL,
    updated_by uuid NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_site_navigation_item_translation PRIMARY KEY (id),
    CONSTRAINT uq_site_navigation_item_translation_locale UNIQUE (site_navigation_item_id, language_code),
    CONSTRAINT ck_site_navigation_item_translation_locale CHECK (language_code IN ('fa', 'en')),
    CONSTRAINT ck_site_navigation_item_translation_label CHECK (btrim(label) <> ''),
    CONSTRAINT fk_site_navigation_item_translation_parent FOREIGN KEY (site_navigation_item_id) REFERENCES site_navigation_item (id) ON DELETE CASCADE,
    CONSTRAINT fk_site_navigation_item_translation_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_navigation_item_translation_updated_by FOREIGN KEY (updated_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_site_navigation_item_translation_deleted_by FOREIGN KEY (deleted_by) REFERENCES app_user (id) ON DELETE SET NULL
);

CREATE TABLE content_page_block (
    id uuid NOT NULL,
    content_page_id uuid NOT NULL,
    block_type varchar(64) NOT NULL,
    sort_order integer NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    settings_json text NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid NULL,
    updated_by uuid NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_content_page_block PRIMARY KEY (id),
    CONSTRAINT ck_content_page_block_type CHECK (block_type IN ('HERO', 'RICH_TEXT', 'MEDIA', 'MEDIA_TEXT', 'CALL_TO_ACTION', 'COLLECTION', 'SKILLS', 'RESUME', 'SOCIAL_LINKS', 'CONTACT')),
    CONSTRAINT ck_content_page_block_order CHECK (sort_order >= 0),
    CONSTRAINT uq_content_page_block_order UNIQUE (content_page_id, sort_order),
    CONSTRAINT fk_content_page_block_page FOREIGN KEY (content_page_id) REFERENCES content_page (id) ON DELETE CASCADE,
    CONSTRAINT fk_content_page_block_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_content_page_block_updated_by FOREIGN KEY (updated_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_content_page_block_deleted_by FOREIGN KEY (deleted_by) REFERENCES app_user (id) ON DELETE SET NULL
);
CREATE INDEX ix_content_page_block_page_order ON content_page_block (content_page_id, sort_order, id) WHERE deleted_at IS NULL;

CREATE TABLE content_page_block_translation (
    id uuid NOT NULL,
    content_page_block_id uuid NOT NULL,
    language_code varchar(2) NOT NULL,
    title varchar(255) NULL,
    eyebrow varchar(255) NULL,
    lead text NULL,
    body_markdown text NULL,
    action_label varchar(255) NULL,
    action_path varchar(2048) NULL,
    alt_text varchar(500) NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    created_by uuid NULL,
    updated_by uuid NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL,
    version bigint NOT NULL DEFAULT 0,
    CONSTRAINT pk_content_page_block_translation PRIMARY KEY (id),
    CONSTRAINT uq_content_page_block_translation_locale UNIQUE (content_page_block_id, language_code),
    CONSTRAINT ck_content_page_block_translation_locale CHECK (language_code IN ('fa', 'en')),
    CONSTRAINT fk_content_page_block_translation_parent FOREIGN KEY (content_page_block_id) REFERENCES content_page_block (id) ON DELETE CASCADE,
    CONSTRAINT fk_content_page_block_translation_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_content_page_block_translation_updated_by FOREIGN KEY (updated_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_content_page_block_translation_deleted_by FOREIGN KEY (deleted_by) REFERENCES app_user (id) ON DELETE SET NULL
);
